In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv("train_data.csv")
df.head()

,Date,ZC025YR,ZC050YR,ZC075YR,ZC100YR,ZC200YR,ZC500YR,ZC1000YR,ZC2000YR,ZC3000YR
0,2016-05-19,0.005283,0.005640,0.005846,0.006051,0.006146,0.007912,0.014099,0.021224,0.020492
1,2016-05-20,0.005286,0.005642,0.005848,0.006053,0.006176,0.007922,0.014179,0.021353,0.020625
2,2016-05-24,0.005298,0.005651,0.005856,0.006062,0.006228,0.008108,0.014379,0.021534,0.020793
3,2016-05-25,0.005351,0.005603,0.005809,0.006014,0.006281,0.008323,0.014548,0.021596,0.020855
4,2016-05-26,0.005354,0.005605,0.005811,0.006016,0.006115,0.007934,0.013937,0.021326,0.020591

In [4]:
df = pd.read_csv("test_data.csv")
df.head()

         Date   ZC025YR   ZC050YR   ZC075YR   ZC100YR   ZC200YR
0  2024-04-29  0.049144  0.048110  0.047051  0.046014  0.042459
1  2024-04-30  0.049156  0.048084  0.047068  0.046093  0.042923
2  2024-05-01  0.049100  0.048083  0.047029  0.046004  0.042449
3  2024-05-02  0.048921  0.047969  0.046831  0.045710  0.041908
4  2024-05-03  0.048633  0.047609  0.046424  0.045235  0.041072

In [5]:
df = pd.read_csv("test_data_3M.csv")
df.head()

         Date   ZC025YR
0  2024-04-29  0.049144
1  2024-04-30  0.049156
2  2024-05-01  0.049100
3  2024-05-02  0.048921
4  2024-05-03  0.048633